[build]
rustflags = ["--cap-lints", "warn"]

# The core Rust library is distributed together with the Rust compiler as a
# precompiled library. It is only valid for supported host triples. For custom
# host triples, we need to recompile core and other standard library crates on
# demand using the build-std feature.
[unstable]
bindeps = true
